import { Projects } from "./projects";
import { Header } from "./header";
import type { NextPage } from "next";
import Head from "next/head";
// import buat bagian cek me out
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faLinkedin,
  faGithub,
  faSteam,
} from "@fortawesome/free-brands-svg-icons";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rel's personal vault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <div className="bg-black flex flex-col">
          <h2 className="text-5xl  mt-24 mb-16 mr-16 text-white text-right">
            Quick Profile
          </h2>
        </div>

        {/* Past Projects */}
        <Projects />

        <div className="bg-black flex flex-col items-center">
          <h2 className="text-5xl  mt-24 mb-16 text-white text-center">
            Check Me Out!
          </h2>
          <div className="flex flex-row gap-8 mb-8">
            <FontAwesomeIcon icon={faLinkedin} size="4x" />
            <FontAwesomeIcon icon={faGithub} size="4x" />
            <FontAwesomeIcon icon={faSteam} spin size="4x" />
          </div>
        </div>

        <div
          className={
            "min-h-screen flex flex-col items-center justify-center h-4/6"
          }
        >
          <video
            autoPlay
            playsInline
            loop
            muted
            className={"absolute w-full h-full object-cover blur-md"}
          >
            <source src="/bg-3.mp4" type="video/mp4; codec=H264" />
          </video>
          <div className="z-10 text-center text-white">
            <h1 className="text-6xl ">Thanks! </h1>
            <div className="flex flex-row gap-8">
              <span className="text-2xl mt-8 ">Terimakasih!</span>
              <span className="text-2xl mt-8">ありがとう!</span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
